[project]
name = "lesson-06-pytests"
version = "0.1.0"
description = "Demo project for python code test lesson"
readme = "README.md"
requires-python = "==3.11.*"
dependencies = [
    "numpy==1.23.2",
    "pandas==1.5.3",
]

[dependency-groups]
dev = [
    "pytest>=9.1.0",
    "pytest-cov>=7.1.0",
]
