# Установите максимально допустимую длину строки —

# Основные настройки
line-length = 120 # Максимальная длина строки для кода
indent-width = 4 # Ширина отступа


# Укажите целевую версию Python — важно для правильной работы ренеймера, парсера и проверки синтаксиса
target-version = "py311"

fix = true

[lint]
select = ["E", "F", "I", "UP", "B", "SIM"]
fixable = ["E", "F", "I", "UP", "B", "SIM"]
unfixable = []

[format]
quote-style = "double"
indent-style = "space"
line-ending = "auto"
skip-magic-trailing-comma = false
