[project]
name = "lesson4"
version = "0.1.0"
description = "Demo project for formatting and linting with ruff"
readme = "README.md"
requires-python = "==3.11.*"
dependencies = [
  "pandas==2.3.3",
  "numpy==2.4.0",
  "joblib==1.5.3",
  "scikit-learn==1.8.0",
  "pydantic==2.12.5",
]

[dependency-groups]
dev = [
    "mypy==1.19.1",
    "pre-commit==4.5.1",
    "ruff==0.14.11",
]

[tool.mypy]
python_version = "3.11"
# Требует аннотации для всех функций
disallow_untyped_defs = true
# Предупреждает, если функция может вернуть Any
warn_return_any = true
# Игнорирует библиотеки без типов (например, старые или научные)
ignore_missing_imports = true 
